name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --name mongodb

      app:
        image: node:20-bullseye-slim
        ports: 
          - 3000:3000
        steps:
          - name: Install Dependencies
            run: npm install
            working-directory: ./backend
          - name: Start Application
            run: npm run serve

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' 

    - name: Install cypress Dependencies
      run: npm ci

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run serve
        wait-on: 'http://localhost:3000'