name: Node.js Tests with MongoDB

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --name mongodb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install project dependencies
      run: |
        cd ./backend
        npm install
      working-directory: ./backend

    - name: Run tests
      run: |
        cd ./backend
        npm run test
      working-directory: ./backend
