name: Node.js Tests with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

services:
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    options: --name mongodb

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Run backend tests
      run: npm run test
      working-directory: ./backend

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start Express.js server
        run: npm start &
        background: true

      - name: Wait for server to start
        run: sleep 10

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        run: npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:3000